Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 536, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import uproot
f = uproot.open('root://eospublic.cern.ch//eos/opendata/cms/datascience/HiggsToBBNtupleProducerTool/HiggsToBBNTuple_HiggsToBB_QCD_RunII_13TeV_MC/train/ntuple_merged_10.root')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
[0;32m/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/cachetools/cache.py[0m in [0;36m__getitem__[0;34m(self, key)[0m
[1;32m     38[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 39[0;31m             [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m__data[0m[0;34m[[0m[0mkey[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     40[0m         [0;32mexcept[0m [0mKeyError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mKeyError[0m: 0

During handling of the above exception, another exception occurred:

[0;31mKeyError[0m                                  Traceback (most recent call last)
[0;32m/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/uproot/source/chunked.py[0m in [0;36mdata[0;34m(self, start, stop, dtype)[0m
[1;32m    116[0m                 [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 117[0;31m                     [0mchunk[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mcache[0m[0;34m[[0m[0mchunkindex[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    118[0m                 [0;32mexcept[0m [0mKeyError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/uproot/cache.py[0m in [0;36m__getitem__[0;34m(self, where)[0m
[1;32m     62[0m         [0;32mwith[0m [0mself[0m[0;34m.[0m[0m_lock[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 63[0;31m             [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_cache[0m[0;34m[[0m[0mwhere[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     64[0m [0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/cachetools/lru.py[0m in [0;36m__getitem__[0;34m(self, key, cache_getitem)[0m
[1;32m     13[0m     [0;32mdef[0m [0m__getitem__[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mkey[0m[0;34m,[0m [0mcache_getitem[0m[0;34m=[0m[0mCache[0m[0;34m.[0m[0m__getitem__[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 14[0;31m         [0mvalue[0m [0;34m=[0m [0mcache_getitem[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mkey[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     15[0m         [0mself[0m[0;34m.[0m[0m__update[0m[0;34m([0m[0mkey[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/cachetools/cache.py[0m in [0;36m__getitem__[0;34m(self, key)[0m
[1;32m     40[0m         [0;32mexcept[0m [0mKeyError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 41[0;31m             [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m__missing__[0m[0;34m([0m[0mkey[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     42[0m [0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/cachetools/cache.py[0m in [0;36m__missing__[0;34m(self, key)[0m
[1;32m     67[0m     [0;32mdef[0m [0m__missing__[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mkey[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 68[0;31m         [0;32mraise[0m [0mKeyError[0m[0;34m([0m[0mkey[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     69[0m [0;34m[0m[0m

[0;31mKeyError[0m: 0

During handling of the above exception, another exception occurred:

[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/uproot/source/xrootd.py[0m in [0;36m_open[0;34m(self)[0m
[1;32m     27[0m             [0mos[0m[0;34m.[0m[0menviron[0m[0;34m[[0m[0;34m"XRD_RUNFORKHANDLER"[0m[0;34m][0m [0;34m=[0m [0;34m"1"[0m   [0;31m# To make uproot + xrootd + multiprocessing work[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 28[0;31m             [0;32mimport[0m [0mpyxrootd[0m[0;34m.[0m[0mclient[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     29[0m         [0;32mexcept[0m [0mImportError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'pyxrootd'

During handling of the above exception, another exception occurred:

[0;31mImportError[0m                               Traceback (most recent call last)
[0;32m<ipython-input-1-6019412c3688>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;32mimport[0m [0muproot[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mf[0m [0;34m=[0m [0muproot[0m[0;34m.[0m[0mopen[0m[0;34m([0m[0;34m'root://eospublic.cern.ch//eos/opendata/cms/datascience/HiggsToBBNtupleProducerTool/HiggsToBBNTuple_HiggsToBB_QCD_RunII_13TeV_MC/train/ntuple_merged_10.root'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/uproot/rootio.py[0m in [0;36mopen[0;34m(path, localsource, xrootdsource, httpsource, **options)[0m
[1;32m     55[0m [0;34m[0m[0m
[1;32m     56[0m     [0;32melif[0m [0m_bytesid[0m[0;34m([0m[0mparsed[0m[0;34m.[0m[0mscheme[0m[0;34m)[0m [0;34m==[0m [0;34mb"root"[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 57[0;31m         [0;32mreturn[0m [0mxrootd[0m[0;34m([0m[0mpath[0m[0;34m,[0m [0mxrootdsource[0m[0;34m=[0m[0mxrootdsource[0m[0;34m,[0m [0;34m**[0m[0moptions[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     58[0m [0;34m[0m[0m
[1;32m     59[0m     [0;32melif[0m [0m_bytesid[0m[0;34m([0m[0mparsed[0m[0;34m.[0m[0mscheme[0m[0;34m)[0m [0;34m==[0m [0;34mb"http"[0m [0;32mor[0m [0m_bytesid[0m[0;34m([0m[0mparsed[0m[0;34m.[0m[0mscheme[0m[0;34m)[0m [0;34m==[0m [0;34mb"https"[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/uproot/rootio.py[0m in [0;36mxrootd[0;34m(path, xrootdsource, **options)[0m
[1;32m     75[0m     [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m     76[0m         [0mopenfcn[0m [0;34m=[0m [0mxrootdsource[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 77[0;31m     [0;32mreturn[0m [0mROOTDirectory[0m[0;34m.[0m[0mread[0m[0;34m([0m[0mopenfcn[0m[0;34m([0m[0mpath[0m[0;34m)[0m[0;34m,[0m [0;34m**[0m[0moptions[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     78[0m [0;34m[0m[0m
[1;32m     79[0m [0;32mdef[0m [0mhttp[0m[0;34m([0m[0mpath[0m[0;34m,[0m [0mhttpsource[0m[0;34m=[0m[0mHTTPSource[0m[0;34m.[0m[0mdefaults[0m[0;34m,[0m [0;34m**[0m[0moptions[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/uproot/rootio.py[0m in [0;36mread[0;34m(source, *args, **options)[0m
[1;32m    120[0m                 [0;31m# See https://root.cern/doc/master/classTFile.html[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m    121[0m                 [0mcursor[0m [0;34m=[0m [0mCursor[0m[0;34m([0m[0;36m0[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 122[0;31m                 [0mmagic[0m[0;34m,[0m [0mfVersion[0m [0;34m=[0m [0mcursor[0m[0;34m.[0m[0mfields[0m[0;34m([0m[0msource[0m[0;34m,[0m [0mROOTDirectory[0m[0;34m.[0m[0m_format1[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    123[0m                 [0;32mif[0m [0mmagic[0m [0;34m!=[0m [0;34mb"root"[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    124[0m                     [0;32mraise[0m [0mValueError[0m[0;34m([0m[0;34m"not a ROOT file (starts with {0} instead of 'root')\n   in file: {1}"[0m[0;34m.[0m[0mformat[0m[0;34m([0m[0mrepr[0m[0;34m([0m[0mmagic[0m[0;34m)[0m[0;34m,[0m [0msource[0m[0;34m.[0m[0mpath[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/uproot/source/cursor.py[0m in [0;36mfields[0;34m(self, source, format)[0m
[1;32m     44[0m         [0mstart[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mindex[0m[0;34m[0m[0;34m[0m[0m
[1;32m     45[0m         [0mstop[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mindex[0m [0;34m=[0m [0mstart[0m [0;34m+[0m [0mformat[0m[0;34m.[0m[0msize[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 46[0;31m         [0;32mreturn[0m [0mformat[0m[0;34m.[0m[0munpack[0m[0;34m([0m[0msource[0m[0;34m.[0m[0mdata[0m[0;34m([0m[0mstart[0m[0;34m,[0m [0mstop[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     47[0m [0;34m[0m[0m
[1;32m     48[0m     [0;32mdef[0m [0mfield[0m[0;34m([0m[0mself[0m[0;34m,[0m [0msource[0m[0;34m,[0m [0mformat[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/uproot/source/chunked.py[0m in [0;36mdata[0;34m(self, start, stop, dtype)[0m
[1;32m    117[0m                     [0mchunk[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mcache[0m[0;34m[[0m[0mchunkindex[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m    118[0m                 [0;32mexcept[0m [0mKeyError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 119[0;31m                     [0mself[0m[0;34m.[0m[0m_open[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    120[0m                     [0mchunk[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_read[0m[0;34m([0m[0mchunkindex[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    121[0m [0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/uproot/source/xrootd.py[0m in [0;36m_open[0;34m(self)[0m
[1;32m     28[0m             [0;32mimport[0m [0mpyxrootd[0m[0;34m.[0m[0mclient[0m[0;34m[0m[0;34m[0m[0m
[1;32m     29[0m         [0;32mexcept[0m [0mImportError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 30[0;31m             [0;32mraise[0m [0mImportError[0m[0;34m([0m[0;34m"Install pyxrootd package with:\n    conda install -c conda-forge xrootd\n(or download from http://xrootd.org/dload.html and manually compile with cmake; setting PYTHONPATH and LD_LIBRARY_PATH appropriately)."[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     31[0m [0;34m[0m[0m
[1;32m     32[0m         [0;32mif[0m [0mself[0m[0;34m.[0m[0m_source[0m [0;32mis[0m [0;32mNone[0m [0;32mor[0m [0;32mnot[0m [0mself[0m[0;34m.[0m[0m_source[0m[0;34m.[0m[0mis_open[0m[0;34m([0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mImportError[0m: Install pyxrootd package with:
    conda install -c conda-forge xrootd
(or download from http://xrootd.org/dload.html and manually compile with cmake; setting PYTHONPATH and LD_LIBRARY_PATH appropriately).
ImportError: Install pyxrootd package with:
    conda install -c conda-forge xrootd
(or download from http://xrootd.org/dload.html and manually compile with cmake; setting PYTHONPATH and LD_LIBRARY_PATH appropriately).

